# Action name here
name: Build & Release

on:
  # Allows manual triggering
  workflow_dispatch:

jobs:
  build-app:
    name: Build executable
    runs-on: [ubuntu-latest]
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          set-safe-directory: true
      - name: Setup environment
        uses: ./.github/actions/setup-env
      - name: Build executable
        run: |
          rm -rf dist
          python3 -m build
      - name: Install sanity test
        run: pip install dist/*.whl
      - name: Import sanity test
        shell: python
        run: |
          try:
            import jmenu.main
            print(jmenu.main.get_version())
            exit(0)
          except ModuleNotFoundError:
            exit(1)
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
