# Action name here
name: Build & Release

on:
  # Allows manual triggering
  workflow_dispatch:

jobs:
  build-app:
    name: Build executable
    runs-on: [ubuntu-latest]
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          set-safe-directory: true
      - name: Setup environment
        uses: ./.github/actions/setup-env
      - name: Export version information
        run: |
          echo "Version ${{ github.ref_name }}"
          echo "VERSION = '${{ github.ref_name }}'" > src/jmenu/version.py
      - name: Build executable
        run: python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
